version: '3.9'

services:
  db:
    container_name: articlerater_postgres
    image: postgres:14
    environment:
      POSTGRES_USER: "postgres_db"
      POSTGRES_PASSWORD: "postgres_db"
      POSTGRES_DB: "postgres_db"
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    container_name: articlerater_redis
    image: redis:latest
    ports:
      - "6380:6379"

  web:
    build: .
    container_name: articlerater_web
    command: gunicorn articlerater.wsgi:application --bind 0.0.0.0:8000
    environment:
      DATABASE_NAME: postgres_db
      DATABASE_USER: postgres_db
      DATABASE_PASSWORD: postgres_db
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  celery:
    build: .
    container_name: articlerater_celery
    command: celery -A articlerater worker -l info
    environment:
      DATABASE_NAME: postgres_db
      DATABASE_USER: postgres_db
      DATABASE_PASSWORD: postgres_db
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    restart: always

  celery_beat:
    build: .
    container_name: articlerater_celery_beat
    command: celery -A articlerater beat -l info
    environment:
      DATABASE_NAME: postgres_db
      DATABASE_USER: postgres_db
      DATABASE_PASSWORD: postgres_db
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    restart: always

volumes:
  db_data:
