# Generated by Django 5.1.4 on 2024-12-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="ratings_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="article",
            name="ratings_sum",
            field=models.IntegerField(default=0),
        ),
    ]
